-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.employee
(
    "id " integer,
    name text,
    PRIMARY KEY ("id ")
);

CREATE TABLE IF NOT EXISTS public.employee_adress
(
    id integer,
    emp_id integer,
    addr1 text,
    addr2 text,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY ("id ")
    REFERENCES public.employee_adress (emp_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;